import Head from 'next/head'
import styles from "../styles/Home.module.css"
import axios from "axios";
import mysql from "mysql2/promise"

export default function Home({users}) {
  console.log(users)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description"
              content="Generated by create next app"/>
        <meta name="viewport"
              content="width=device-width, initial-scale=1"/>
        <link rel="icon"
              href="/favicon.ico"/>
      </Head>
      home
    </>
  )
}

export const getStaticProps = async () => {
  const connection = await mysql.createConnection({
    host: 'localhost',
    user: 'root',
    database: 'schema_name'
  });

  const [rows, fields] = await connection.execute("SELECT * FROM student");

  return {
    props: {
      users: rows
    }
  }
};